In [1]:
# Pytorch Basic

In [4]:
import torch

In [5]:
torch.cuda.is_available()

False

In [6]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("./Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
x = df.drop(["Species"], axis = 1).values
y = le.fit_transform(df["Species"].values)

x.shape

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.FloatTensor(y_train).reshape(-1,1)
y_test = torch.FloatTensor(y_test).reshape(-1,1)


In [19]:
len(y_train)

120

In [20]:
labls, counts = y_train.unique(return_counts=True)
print(labls,counts)

tensor([0., 1., 2.]) tensor([40, 41, 39])


In [21]:
import torch

In [23]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [24]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [33]:
y.grad_fn

In [1]:
y.backward()

NameError: name 'y' is not defined

In [39]:
x.grad

tensor(93.)

In [ ]:
# BTVN 1:
# cho y = 5x^6 + 6x^3 - 3x +1
# cho biết độ dốc của đa thức trên ở điểm nào

In [ ]:
# BTVN 2:
# tạo một tensor ban đầu có giá trị là 2
# Định nghĩa hàm số và tính gradient
# y = x^3 +2x^2 + 5x + 1
# hãy tính dy/dx tại giá trị của x
# Dùng phương pháp Gradient Descent của learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lập

# BTVN 3:
# Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm đc tính theo công thức y = 3x + 5 + noise với noise là mooyj giá trị ngẫu nhiên nhỏ

# 1. khởi tạo tham ư và b ngẫu nhiên với requires_grad = True
# 2. Tính MSE
# 3. Tính Gradient
# 4. Cập nhật tham số ư và b bằng Gradient Descent với learning rate alpha = 0.01
# 5. lập lại quá trùng trên trong 100 vòng lặp để xem sự hội tụ của mô hình

In [40]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [41]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [42]:
print(x.dtype)

torch.int32


In [43]:
print(x.type())

torch.IntTensor


In [44]:
arr2 = np.arange(0.,12).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [45]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [46]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5], dtype=torch.int32)


In [47]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [48]:
arr[0]=99
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [ ]:
#BTVN 4: giải thích 2 trường hợp ở trên

In [ ]:
#BTVN 5:
# Bạn giúp thầy tạo tensor với
# empyty
# zeros
# ones
# random
# reshape với view và view as 