In [4]:
import numpy as np

In [5]:
python_list = [1, 2, 3]

# chuyen doi danh sach python sang numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [6]:
my_list = [1, 'chap', True, 2.0]

In [7]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [8]:
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [9]:
x = np.array([1,2,3,4,5,6,7,8])

In [10]:
print(x[3])

4


In [11]:
#lấy nhiều hơn 1 phần tử
#công thức
#lấy 1 2 3

x[0:3]

array([1, 2, 3])

In [12]:
# lấy từ 2 - 8 theo 3 cách
#c1
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [13]:
#c2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [14]:
#lấy 3 và 5
x[2:5]

array([3, 4, 5])

In [15]:
#c2
x[2] ,x[4]

(3, 5)

In [16]:
# đặt danh sách các index muốn truy cập

x[[2,4]]

array([3, 5])

In [17]:
np_list = np.array([[1,2],[3,4],[5,6]])


In [18]:
#lấy 3,4 5,6
#c1
np_list[1:,:]

array([[3, 4],
       [5, 6]])

In [19]:
#c2
np_list[[1,2],:]

array([[3, 4],
       [5, 6]])

In [20]:
#c3
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [21]:
#lấy 1,3,5
np_list[:,0]

array([1, 3, 5])

In [22]:
#lấy 1 và 5 theo 2 cách
#c1
np_list[[0,2],0]

array([1, 5])

In [23]:
#c2
np_list[0::2,0]

array([1, 5])

In [24]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list = np.array(x)

np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
np_list[:,1]

array([ 2,  6, 10, 14])

In [26]:
np_list[[1,2],2]

array([ 7, 11])

In [27]:
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [ ]:
# BTVN 1
# cho ma trận = [[99,99,99],
#                [99,99,99],
#                [99,99,99]]

# hãy tưởng tượng ô 99 trống
# giả sử 1 là x
# Giả sử 0 là o

# Lấy đầu vào từ phía X và phía O luân phiên
# Nếu đầu vào từ phía X là (0,0)

# ma trận sẽ trở thành
# [[x,99,99],
#  [99,99,99],
#  [99,99,99]]

# nếu không thì điền vào ma trận

# Thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi

In [ ]:
# BTVN 2

y = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# lấy 4,5,6
# lấy 2,5
# lấy 3,4
# lấy 9,6,3


In [29]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [32]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [33]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
idx = ([ True, False,  True, False,  True, False,  True, False,  True, False])
np_x[idx]

array([0, 2, 4, 6, 8])

In [ ]:
# BTVN 3

# cho x = [1,2,3,4,5,6,7,8,9,10]

# 1. Xuất ra các giá trị chẵn sử dụng if
# 2. Xuất ra các giá trị chẵn sử dụng list comprehension

In [ ]:
# BTVN 4

# tạo một mảng numpy có kích thước 150 x 5 .
# Giả sử mảng này chứa 150 mẫu dữ liệu của sinh viên
# bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình

# Tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là X
# và cột cuối cùng thành y

# tách X thành X_train và X_test trong đó X_train chứa 70% dữ liệu
# và tách y thành y_train và y_test, trong đó y_train chứa 70% dữ liệu

# Tạo 10 tập dữ liệu X_train không chồng chéo nhau
